import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import './globals.css'
import Script from 'next/script'
import Header from './components/Header'
console.log("hello world")
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tarun kataria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <head>
      
      </head>
      <body className={inter.className}>  <Providers>
        <Header/>
        {children} </Providers></body>
    </html>
        <Script src="https://checkout.razorpay.com/v1/checkout.js"/>
        </>
  )
}
